trigger:
  batch: "true"
  branches:
    include: [master, test-*]
  tags:
    include: ["*"]

resources:
  repositories:
    - repository: aleksac
      type: github
      endpoint: AleksaC
      name: AleksaC/azure-pipelines-templates
      ref: refs/tags/v0.0.6

jobs:
  - template: jobs/python-tests.yml@aleksac
    parameters:
      toxenvs: [ py36 ]
      coverage: false

  - template: jobs/python-tests.yml@aleksac
    parameters:
      os: windows
      toxenvs: [ py36 ]
      coverage: false

  - template: jobs/python-tests.yml@aleksac
    parameters:
      os: macos
      toxenvs: [ py36 ]
      coverage: false
