name: Add new versions

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  add_new_versions:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ env.GH_TOKEN }}

      - name: Set up python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure git
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Add new versions
        run: ./add-new-versions.py --push
